import type { WeekData } from "@/lib/mfa/types";

export const week8Data: WeekData = {
  weekNumber: 8,
  totalWeeks: 36,
  semesterLabel: "Fall Semester",
  phaseLabel: "Specialization",
  title: "Theme & Meaning — What Is This Piece Actually About?",
  emphasizedWord: "What Is This Piece Actually About?",
  deck: "Theme is not a message or a lesson. A theme is not what a piece of writing says — it is what it asks. The best literary works are organized around questions, not arguments. Beloved is not a piece of writing about slavery's horror — it is a piece of writing asking what freedom means when memory itself is a form of haunting. The Great Gatsby is not an argument against the American Dream — it is an investigation of what happens to people who mistake the dream's symbols for the dream itself.",
  meta: [
    { label: "Commitment", value: "12–18 hrs" },
    { label: "Program Week", value: "44 of 108" },
    { label: "Craft Focus", value: "Theme & Meaning" },
    { label: "Grammar", value: "Phase 3 · Gerunds & Infinitives" },
    { label: "Thesis Target", value: "1,500–2,000 words" },
  ],
  sections: [
    {
      id: "lecture",
      label: "Craft Lecture",
      title: "The Question the Work Is Asking",
      blocks: [
        {
          type: "paragraph",
          content: [
            "Theme is the most misunderstood concept in craft instruction, largely because the word has been hijacked by two different and equally wrong definitions. The first wrong definition: theme as topic ('the theme of this novel is war'). A topic is not a theme — it is a subject. War is a subject. What war does to the people who survive it is a theme, or the beginning of one. The second wrong definition: theme as moral ('the theme of this story is that greed corrupts'). A moral is not a theme — it is a conclusion. Theme is not a conclusion. It is an inquiry. The work that begins knowing its moral has nowhere to go; the work that begins with a genuine question has a destination it cannot yet see, and the movement toward that destination is what generates the story's energy.",
          ],
        },
        {
          type: "paragraph",
          content: [
            "The distinction that matters: theme is ",
            { text: "what the work asks,", emphasized: true },
            " not what it says. And the question must be one to which the writer does not already know the answer — or at least one to which the writer suspects their known answer is wrong, insufficient, or incomplete. The writer who knows what they think about their subject before they write it is not conducting an inquiry; they are illustrating a position. Illustration can be technically accomplished. It cannot achieve the particular quality of literary art, which is the quality of ",
            { text: "discovery —", emphasized: true },
            " the sense that the writer is finding something out in the process of writing, that the work has led them somewhere they did not plan to go.",
          ],
        },
        {
          type: "pullquote",
          quote: "Theme in literary fiction is usually discovered through drafting, not planned. The revision process is where the writer identifies what the work has been about all along — and deepens it.",
          cite: "— craft principle",
        },
        {
          type: "card",
          title: "Three Ways Theme Operates Structurally",
          paragraphs: [
            "Theme is generated by the collision of character desire and story situation. The character who wants something specific — not 'love' but 'this particular person's love', not 'success' but 'my father's acknowledgment of my success' — is placed in a situation that systematically frustrates or complicates that want. The collision between what the character desires and what the situation allows is where theme is produced: not planned by the writer in advance but generated by the pressure of the story. *Beloved*'s theme — the question of what freedom means when memory itself is a form of haunting — is not a decision Toni Morrison made before writing. It is what the collision between Sethe's desire to be free and the situation of slavery's aftermath inevitably produced. The writer who wants to deepen their theme should deepen the collision between desire and situation, not add more explicit discussion of the theme.",
            "Theme is carried by image, not by statement. The work's governing images — the images that recur, that accumulate meaning across the work's length, that appear at moments of maximum significance — are the theme's primary vehicle. The snow in 'The Dead' is not a symbol that Joyce attached to the theme he had already worked out. It is the theme made concrete — the extension of Gabriel's vision beyond the personal, the formal image of what the story's question looks like when it is finally visible. When a writer identifies their theme and then asks where it is most alive in the manuscript, the answer is almost always in the images: the recurring objects, the repeated settings, the motifs that have been present from the beginning without the writer fully understanding why. Those are where the theme lives.",
            "Theme operates at the level of the governing question, not the controlling statement. McKee's 'controlling idea' — theme expressed as a declarative sentence — is useful for screenwriters who need to pitch their work and for writers who need a compass during drafting. But in literary prose, the governing question is more generative than the controlling statement, because the question preserves the work's capacity for discovery. 'What does love cost?' is more productive than 'Love costs everything' because the question remains open to findings the draft may produce. The statement closes down; the question opens up. The writer whose governing question is genuinely open — who does not know the answer — is the writer whose work has the possibility of surprising them.",
          ],
        },
        {
          type: "paragraph",
          content: [
            "The thematic pressure test is this week's primary analytical tool applied to the thesis draft: for every scene in the current manuscript, ask whether the scene is in active engagement with the governing question. A scene that advances plot without touching the governing question is thematically inert — it may be well-written, it may be necessary for the surface narrative, but it is not doing the thematic work the manuscript needs. The revision of thematically inert scenes is not the addition of explicit thematic content — it is the deepening of the collision between character desire and situation that the scene already contains, so that the governing question becomes present in the scene without being announced.",
          ],
        },
      ],
    },

    {
      id: "cross-genre",
      label: "Cross-Genre Note",
      title: "Theme Across Forms",
      blocks: [
        {
          type: "genreGrid",
          items: [
            {
              badge: "Literary Fiction",
              variant: "lf",
              text: "Theme in literary fiction is usually discovered through drafting, not planned. The writer who plans their theme in advance and then writes toward it is doing a different and lesser thing than the writer who drafts without knowing what the work is about and discovers, in revision, that it has been about one thing all along. The revision process is where the writer identifies what the work has been about and deepens it — makes the governing question more fully present in every scene, develops the images that carry it, cuts the scenes that do not engage it. The writer who reaches the end of a draft and cannot state the governing question probably does not yet have one — and the necessary response is not to add one but to reread the draft and find the question that was already there, latent in the material, waiting to be named.",
            },
            {
              badge: "Screenwriting & Playwriting",
              variant: "sp",
              text: "Theme in screenwriting is often stated more explicitly — the 'spine' of the script that every scene should be doing something to advance. McKee's concept of 'controlling idea' is theme formalized as a sentence: 'Justice is served when the detective sacrifices his personal happiness for truth.' This formalization is useful for pitching and for keeping the script coherent across a long production process — but it can also calcify theme into ideology, making the work didactic rather than inquiring. The most sophisticated screenwriters hold the controlling idea lightly: as a compass during drafting, but not as a constraint that prevents the story from finding something more complex than its initial formulation. For playwrights, theme is often most alive in the play's silences — in what the characters cannot say, in the questions the dialogue raises without answering.",
            },
            {
              badge: "Creative Nonfiction & Memoir",
              variant: "cnf",
              text: "In the essay, the theme is the essay's inquiry — the question the writer is genuinely trying to answer. If the writer already knows the answer before writing, the essay has no intellectual momentum: it becomes a vehicle for delivering a conclusion the writer arrived at elsewhere, and the reader feels the absence of genuine investigation. The most powerful essays are ones in which the writer's relationship to the question changes across the essay's length — in which the writing has done something to the writer's understanding, so that the essay ends in a different place than it began. This is what Didion meant when she said she wrote to find out what she thought. The essay is not the record of what you thought before writing; it is the record of what writing made you think.",
            },
          ],
        },
      ],
    },

    {
      id: "grammar",
      label: "Grammar & Style",
      title: "Phase 3 · Topic 8 — Gerunds & Infinitives: Action Nominalized",
      blocks: [
        {
          type: "grammar",
          title: "Phase 3 · Topic 44 of 60 — Gerunds and Infinitives: The Weight of Named Action",
          intro: [
            "Gerunds and infinitives are Phase 3's two constructions that nominalize action — that turn doing into naming, converting a verb into a noun. A gerund is a verb form ending in '-ing' used as a noun: running, leaving, waiting, understanding, refusing. An infinitive is 'to' plus the verb's base form used as a noun: to run, to leave, to wait, to understand, to refuse. Both treat action as an object — something that can be the subject of a sentence, the object of a verb, or the object of a preposition — rather than as a predicate.",
            "The nominalization of action creates a specific kind of weight in prose: it makes the action permanent, fixed, available for examination and judgment in a way that the same verb as predicate does not. 'She left' is an event. 'Leaving was the only thing she had ever done that was entirely hers' makes leaving an object — something that can be considered, that has properties (entirely hers), that exists outside the moment of its occurrence.",
          ],
          rule: "The craft distinction between gerunds and infinitives is tonal and philosophical: gerunds tend toward the concrete and ongoing ('Running exhausted her' — the running is experienced, immediate, embodied), while infinitives tend toward the abstract and philosophical ('To run was to refuse everything she had been told to become' — the running is now an idea, a principle, a statement about identity). Both are useful; both can be overused. The diagnostic question for any nominalized action: is the nominalization doing conceptual work — giving the action a weight or a permanence that the predicate form cannot achieve — or is it merely avoiding the more direct and more active predicate version? 'She ran until she was exhausted' is often better than 'Running exhausted her.' It depends on whether the running is the subject of the sentence or the event of the sentence.",
          examples: [
            {
              label: "Gerund as subject — action given weight and permanence",
              text: "'Waiting had become her primary occupation.' [The waiting is not an event here — it is a state, a condition that has taken over, with the permanence of a noun. The predicate version — 'She waited, and it had become her primary occupation' — is less compressed and gives the waiting less weight.]",
            },
            {
              label: "Infinitive as subject — action as philosophical position",
              text: "'To leave was to admit that she had been wrong.' [The infinitive creates an equation: leaving = admitting wrongness. The equation is a philosophical claim, not a narrative event. The predicate version — 'She left, which meant admitting she had been wrong' — is accurate but less compact and less absolute.]",
            },
            {
              label: "Nominalization in service of theme",
              text: "'The refusing of comfort was itself a comfort.' [The gerund phrase 'the refusing of comfort' treats the act of refusing as an object that can have properties — here, the paradoxical property of being comforting. This is the nominalization doing thematic work: making a philosophical claim about the character's relationship to grief that the predicate form cannot make as efficiently.]",
            },
            {
              label: "Overuse — and the predicate that serves better",
              text: "Overused: 'The crossing of the threshold into the room that had been his father's study produced in her a feeling of having returned.' [Three nominalizations — crossing, having returned — that bury the action in abstraction.] Better: 'She crossed the threshold into her father's study and felt, for the first time since his death, that she had returned.' [Predicates do the work; the action is immediate; the feeling follows from it.]",
            },
          ],
          outro: [
            "The relationship between gerunds and infinitives and this week's theme topic is the relationship between named action and meaning: nominalizing an action is one of the ways literary prose makes thematic claims without announcing them. 'To leave was to admit failure' is a thematic statement in grammatical disguise — it claims something about the moral character of the action, about what leaving means in the world of this story. The writer who is attentive to their nominalizations is attending to the places where the prose is making claims about meaning.",
            "The exercise this week develops the diagnostic habit: find the nominalizations in your current draft, assess which are doing conceptual work and which are avoiding the predicate, and develop the ones that are thematically productive while converting the avoidance-nominalizations back to their predicate forms.",
          ],
          exercise:
            "Scan one page of your current thesis draft for gerunds and infinitives used as nouns. For each nominalization: (1) Is it doing conceptual work — giving the action weight or permanence that the predicate form cannot — or is it avoiding the more direct predicate? (2) If avoiding: rewrite as a predicate and compare. (3) If doing conceptual work: is the nominalization making a thematic claim? What is the claim? Write three original sentences using nominalizations to make thematic claims about your thesis's governing question — sentences in which the gerund or infinitive is doing the philosophical work of making the theme present without announcing it.",
        },
      ],
    },

    {
      id: "reading",
      label: "Core Reading",
      title: "This Week's Texts",
      blocks: [
        {
          type: "readingList",
          items: [
            {
              number: "01",
              title: "Mystery and Manners, 'The Nature and Aim of Fiction'",
              author: "Flannery O'Connor",
              href: "https://bookshop.org/p/books/mystery-and-manners-flannery-oconnor/6697453",
              note: "Purchase. O'Connor's essay is the most direct and uncompromising account of what fiction is for — and her account of theme is inseparable from her account of what makes fiction literary rather than merely competent. Read for her distinction between the 'problem novel' (which begins with a thesis and illustrates it) and the literary novel (which begins with an inquiry and discovers its answer in the writing). Apply her account to your own thesis project: is it an illustration or an inquiry? If illustration, where did the thesis form, and can it be converted back to a question?",
              badge: "Purchase",
            },
            {
              number: "02",
              title: "A Swim in a Pond in the Rain, Turgenev's 'The Singers' chapter",
              author: "George Saunders",
              href: "https://bookshop.org/p/books/a-swim-in-a-pond-in-the-rain-george-saunders/14360498",
              note: "Purchase (continuing from Year Two, Week 1). The 'Singers' chapter is Saunders's most lucid account of how theme is generated in fiction — specifically, how it is produced by the story's situation rather than imported from outside it. Read for his account of 'the thing the story is doing' versus 'the thing the writer thinks the story is doing,' and apply the distinction to your own draft. Where are those two things the same, and where do they diverge?",
              badge: "Purchase",
            },
            {
              number: "03",
              title: '"The Theme for English B"',
              author: "Langston Hughes",
              href: "https://www.poetryfoundation.org/poems/47880/theme-for-english-b",
              note: "Free online at the Poetry Foundation. A short poem — read it twice, then read it as a study in theme made structurally explicit. The poem's governing question (what is the relationship between the self and the culture that shaped it, when that culture has also oppressed it?) is not stated in the poem — it is enacted by the poem's form, by the assignment the poem is responding to, by the gap between the instructor's expectation and the student's response. The poem is its own theme. Apply this observation to your thesis: where is the governing question not stated but enacted?",
              badge: "Free Online",
            },
          ],
        },
      ],
    },

    {
      id: "exercise",
      label: "Writing Exercise",
      title: "The Thematic Statement & Pressure Test + Thesis Session 8",
      blocks: [
        {
          type: "exercise",
          paragraphs: [
            "Part One — The Thematic Statement as Question (500 words): Write a 500-word statement of your thesis project's theme — but write it as a question, not a statement. Not 'this work is about grief' or 'this work argues that grief is transformative' but 'what does grief ask of the people who survive it, and what does surviving it cost them?' The question should be: specific enough to be this work's question and not any work's question; genuinely open — you should not know the answer; and present in the material you have already written, not imported from outside it. After writing the question, assess: is this the question the draft is already asking? If the question you have written and the question the draft is asking are different questions, which is right — and what does the discrepancy tell you about what the work actually is?",
            "Part Two — The Thematic Pressure Test (300 words analysis): Identify three scenes from your current draft (or from Year One draft openings) where the governing question is actively engaged — where the collision between character desire and situation is producing the question, where the images are carrying it. Then identify one scene where the thematic pressure is weakest — where the scene advances plot without touching the governing question. Write a 300-word analysis of what would need to change in the thematically inert scene to bring the governing question into active engagement without adding explicit thematic content.",
            "Part Three — Thesis Session 8 (1,500–2,000 words): Write the next section of the thesis with the governing question as a pressure — not a content requirement but a background test. After the session, read the new pages and note in the session log whether the governing question is present in them, and where. If it is absent, identify which of the session's scenes could be deepened without altering its surface content to bring the question into play.",
          ],
          target: "500 words (thematic question) + 300 words (pressure test analysis) + 1,500–2,000 words (thesis session)",
        },
      ],
    },

    {
      id: "ai",
      label: "AI Workshop",
      title: "Exercise 44 — The Thematic Interrogator",
      blocks: [
        {
          type: "ai",
          tool: "Tool: Claude or ChatGPT",
          intro:
            "Describe your protagonist's situation in two to three sentences — their desire, their circumstances, and the primary obstacle or complication they face. The AI's task is to propose possible governing questions that the situation generates, and to identify the 'need beneath the want' that the character's psychology suggests.",
          prompt:
            "I am going to describe my protagonist's situation in two to three sentences. First: propose five possible governing questions that this situation generates — not plot questions (will they get what they want?) but thematic questions (what does the wanting itself reveal about what it means to be human in this situation?). Frame each governing question as a genuine inquiry, not a conclusion. Second: propose five possible 'needs beneath the want' for this character — not what they consciously desire, but what their psychology suggests they are actually hungry for, even if they would never name it. Frame each need as a wound that produces behavior. Use the most resonant combination of governing question and need as the basis for the thematic pressure test. Here is the situation: [describe your protagonist's situation in 2–3 sentences].",
          questions: [
            "Which of the five governing questions most closely matches the question your thesis draft is already asking — the question that is already present in the material, whether or not you have named it? Is that the question you would choose deliberately, or has the material been asking a more interesting question than the one you had in mind?",
            "Which of the five needs beneath the want most resonates as your character's actual hunger — the thing the story is actually about beneath the surface of what the character wants? How would naming this need change your understanding of which scenes are thematically alive and which are thematically inert?",
            "The AI's governing questions are generated from the situation you described. Are any of them questions that your description of the situation does not fully support — questions that would require the situation to be different or more complex? If so, what would the situation need to be to generate that question? Is that a more interesting situation than the current one?",
            "Take the governing question the AI proposed that is furthest from your current understanding of the thesis's theme. What would the thesis look like if that were its real question? Write three sentences describing the work that question would produce. Is it a more interesting work than the one you are writing?",
          ],
          note: "The thematic interrogator uses the AI not to identify your theme for you but to expand the range of thematic possibilities the material might support — to show you questions the situation generates that you may not have seen. The writer whose governing question is the only one they can imagine for their material is the writer who has narrowed their inquiry prematurely. The AI's five questions are not five options to choose from; they are evidence of the material's thematic range. The question you choose should be the one that feels most genuinely open — the one to whose answer you are most uncertain.",
        },
      ],
    },

    {
      id: "tip",
      label: "Editorial Tip",
      title: "The Motivation Test",
      blocks: [
        {
          type: "tip",
          icon: "🔍",
          name: "Does Every Major Action Serve Want, Need, or Both?",
          paragraphs: [
            "For every major action your protagonist takes in the draft, ask: does this action serve their stated want, their deeper need, or both simultaneously? The action that serves only the want is plot-functional but thematically thin. The action that serves only the need is thematically rich but may feel unmotivated at the surface level. The action that serves both — that advances the character toward what they consciously want while simultaneously moving them toward what they actually need, even against their resistance — is the action that operates on multiple frequencies simultaneously and produces the kind of scene Week 1 called for.",
            "If you cannot answer the question — if the character's motivation for a major action is unclear — the motivation is unclear to the reader, and they will feel it as unconvincing behavior. The fix is almost never to add an explanation of the motivation; it is to deepen the collision between want and need so that the motivation is legible in the action itself. The character who reaches for what they want in a way that the reader can see is simultaneously moving away from what they need — or toward it against their will — is a character whose motivation is fully present without being stated.",
          ],
        },
      ],
    },

    {
      id: "journal",
      label: "Journal Prompt",
      title: "What You Wanted and What You Needed",
      blocks: [
        {
          type: "journal",
          title: "What You Wanted and What You Needed",
          question:
            "What have you wanted in your life that you worked very hard to get? Not something minor — something that organized a significant period of your life, that you pursued with real commitment, that you either achieved or failed to achieve at real cost. What did getting it — or not getting it — teach you about what you actually needed? Where was the gap between the want and the need, and how long did it take to see it? And: is that gap — between what you pursued and what you required — present anywhere in your thesis? Not as autobiography but as structure: is the collision between want and need, between the thing pursued and the thing actually needed, the collision that generates your work's governing question? If not, what is generating it — and is that the right engine?",
        },
        {
          type: "paragraph",
          className: "italic text-muted",
          content: [
            "The journal prompt this week is an excavation of personal thematic material — not for the purpose of making the thesis autobiographical but for the purpose of understanding what makes a theme feel genuine rather than imported. The want/need gap that generates the most powerful fiction is usually one the writer knows intimately, not because the fiction is about the writer's life but because the writer has lived the emotional logic of the situation. The writer who has felt the specific quality of wanting something that was wrong for them, and the specific quality of discovering what they actually needed, has access to the emotional precision that thematic depth requires.",
          ],
        },
      ],
    },

    {
      id: "summary",
      label: "Week in Summary",
      title: "What You've Built",
      blocks: [
        { type: "divider" },
        {
          type: "paragraph",
          content: [
            "By the end of this week you should have: written the 500-word governing question statement as genuine inquiry rather than conclusion; completed the 300-word thematic pressure test identifying three thematically alive scenes and one thematically inert scene with analysis of what would activate it; written 1,500–2,000 words of thesis in Session 8 with governing question presence noted in the session log; read O'Connor's 'Nature and Aim of Fiction' for the distinction between illustration and inquiry; read Saunders on 'The Singers' for theme generated by situation rather than imported; read Hughes's 'Theme for English B' for governing question enacted rather than stated; completed the AI thematic interrogator and assessed which of the five governing questions the draft is already asking; written three nominalizations that make thematic claims without announcing them; and applied the motivation test to three major protagonist actions in the current draft.",
          ],
        },
        {
          type: "card",
          title: "Looking Ahead to Week 9",
          paragraphs: [
            "Week 9 is Revision I — The Generative vs. the Revisionary Process. Revision is not editing — it is re-vision, a second act of seeing. Week 9 introduces the two-mode revision process, the four-step re-vision protocol, and the Phase 3 phrase toolkit synthesis. The week's primary exercise applies the full re-vision protocol to a Year One piece, building the cold-reading skills that thesis revision will require.",
          ],
        },
      ],
    },
  ],
};
